# Terraform backend configuration for production environment
# Generated by setup-backend.sh with ENVIRONMENT=production
# State is stored separately from staging to enable independent deployments

prefix = "terraform/state/production"
