# Terraform backend configuration for staging environment
# Generated by setup-backend.sh with ENVIRONMENT=staging
# State is stored separately from production to enable independent deployments

prefix = "terraform/state/staging"
