#!/bin/bash

# Exit on error
set -e

# Configuration
BUCKET_NAME=${TF_STATE_BUCKET:-"autonyan-terraform-state"}
LOCATION=${TF_STATE_LOCATION:-"us-central1"}
ENVIRONMENT=${ENVIRONMENT:-"staging"}
PROJECT_ID=$(gcloud config get-value project)

# Validate environment
if [ "$ENVIRONMENT" != "staging" ] && [ "$ENVIRONMENT" != "production" ]; then
	echo "Error: ENVIRONMENT must be 'staging' or 'production'"
	echo "Current value: $ENVIRONMENT"
	exit 1
fi

# Validate inputs
if [ -z "$PROJECT_ID" ]; then
	echo "Error: No Google Cloud project configured"
	echo "Please run: gcloud config set project YOUR_PROJECT_ID"
	exit 1
fi

# Check if bucket exists
if gcloud storage buckets describe "gs://${BUCKET_NAME}" >/dev/null 2>&1; then
	echo "Bucket gs://${BUCKET_NAME} already exists"
else
	echo "Creating GCS bucket for Terraform state..."
	gcloud storage buckets create "gs://${BUCKET_NAME}" \
		--project="${PROJECT_ID}" \
		--location="${LOCATION}" \
		--uniform-bucket-level-access
fi

# Enable versioning (idempotent operation)
echo "Ensuring versioning is enabled..."
gcloud storage buckets update "gs://${BUCKET_NAME}" \
	--versioning

# Set lifecycle policy
echo "Setting lifecycle policy..."
cat >lifecycle-policy.json <<EOF
{
  "rule": [
    {
      "action": {
        "type": "Delete"
      },
      "condition": {
        "numNewerVersions": 10,
        "isLive": false
      }
    }
  ]
}
EOF

# Apply lifecycle policy (idempotent operation)
gcloud storage buckets update "gs://${BUCKET_NAME}" \
	--lifecycle-file=lifecycle-policy.json

# Create environments directory if it doesn't exist
mkdir -p terraform/environments

# Create or update environment-specific backend configuration file
echo "Creating backend configuration for ${ENVIRONMENT} environment..."
cat >"terraform/environments/${ENVIRONMENT}.backend.hcl" <<EOF
# Terraform backend configuration for ${ENVIRONMENT} environment
# Generated by setup-backend.sh with ENVIRONMENT=${ENVIRONMENT}
# State is stored separately from other environments to enable independent deployments

bucket = "${BUCKET_NAME}"
prefix = "terraform/state/${ENVIRONMENT}"
EOF

# Clean up
rm -f lifecycle-policy.json

echo ""
echo "Terraform state bucket setup complete!"
echo "Environment: ${ENVIRONMENT}"
echo "Bucket: gs://${BUCKET_NAME}"
echo "State prefix: terraform/state/${ENVIRONMENT}"
echo "Location: ${LOCATION}"
echo ""
echo "Backend configuration created:"
echo "  - terraform/environments/${ENVIRONMENT}.backend.hcl"
echo ""
echo "To initialize Terraform with this backend, run:"
echo "  ENVIRONMENT=${ENVIRONMENT} terraform init -backend-config=environments/${ENVIRONMENT}.backend.hcl"
echo ""
echo "Or use the npm script (recommended):"
echo "  ENVIRONMENT=${ENVIRONMENT} npm run terraform:init"
