#!/bin/bash

# Exit on error
set -e

# Configuration
TFVARS_FILE="terraform/terraform.tfvars"
ENVIRONMENT=${ENVIRONMENT:-"staging"}

echo "Setting up terraform.tfvars for GitHub Actions..."

# Validate environment
if [ "$ENVIRONMENT" != "staging" ] && [ "$ENVIRONMENT" != "production" ]; then
	echo "Error: ENVIRONMENT must be 'staging' or 'production'"
	echo "Current value: $ENVIRONMENT"
	exit 1
fi

# Get project ID from gcloud CLI
PROJECT_ID=$(gcloud config get-value project)
if [ -z "$PROJECT_ID" ]; then
	echo "Error: No Google Cloud project configured"
	echo "Please run: gcloud config set project YOUR_PROJECT_ID"
	exit 1
fi

# Validate required environment variables
if [ -z "$GCP_REGION" ]; then
	echo "Error: GCP_REGION variable is not set"
	exit 1
fi

if [ -z "$DRIVE_FOLDER_ID" ]; then
	echo "Error: DRIVE_FOLDER_ID secret is not set"
	exit 1
fi

if [ -z "$DRIVE_SCANNER_SCHEDULE" ]; then
	echo "Error: DRIVE_SCANNER_SCHEDULE variable is not set"
	exit 1
fi

if [ -z "$CATEGORY_ROOT_FOLDER_ID" ]; then
	echo "Error: CATEGORY_ROOT_FOLDER_ID secret is not set"
	exit 1
fi

if [ -z "$UNCATEGORIZED_FOLDER_ID" ]; then
	echo "Error: UNCATEGORIZED_FOLDER_ID secret is not set"
	exit 1
fi

# Generate terraform.tfvars from GitHub Actions variables/secrets
echo "Generating terraform.tfvars for ${ENVIRONMENT} environment..."
cat >"$TFVARS_FILE" <<EOF
# Terraform variables for ${ENVIRONMENT} environment
# Generated by setup-terraform-variables.sh

project_id = "$PROJECT_ID"
environment = "$ENVIRONMENT"
region = "$GCP_REGION"
drive_folder_id = "$DRIVE_FOLDER_ID"
drive_scanner_schedule = "$DRIVE_SCANNER_SCHEDULE"
category_root_folder_id = "$CATEGORY_ROOT_FOLDER_ID"
uncategorized_folder_id = "$UNCATEGORIZED_FOLDER_ID"
EOF

echo ""
echo "terraform.tfvars generated successfully"
echo "Environment: $ENVIRONMENT"
echo "Contents (secrets masked):"
echo "  project_id = $PROJECT_ID"
echo "  environment = $ENVIRONMENT"
echo "  region = $GCP_REGION"
echo "  drive_folder_id = [MASKED]"
echo "  drive_scanner_schedule = $DRIVE_SCANNER_SCHEDULE"
echo "  category_root_folder_id = [MASKED]"
echo "  uncategorized_folder_id = [MASKED]"
