# PubSub topic for document scanning preparation
# Receives messages containing Google Drive file IDs for document processing
# Triggers the document scanner function to copy files to Cloud Storage
resource "google_pubsub_topic" "doc_process_trigger" {
  name = "${var.environment}-doc-process-trigger"
}

# Dedicated service account for the document scan preparation function
# Accesses Google Drive through manual folder sharing (not project-level IAM)
# Includes permissions for API access, Cloud Storage, and PubSub
resource "google_service_account" "doc_processor_sa" {
  account_id   = "${var.environment}-doc-processor-sa"
  display_name = "Document Processor Service Account (${var.environment})"
  description  = "Service account for Google Drive access and Cloud Storage operations"
}

# IAM binding for Google Cloud Storage access - Document Scan Preparation
# Grants read/write access to storage objects for the document scan preparation service account
resource "google_project_iam_member" "doc_processor_storage_access" {
  project = var.project_id
  role    = "roles/storage.objectAdmin"
  member  = "serviceAccount:${google_service_account.doc_processor_sa.email}"
}

# IAM binding for Google API service usage - Document Scan Preparation
# Allows the document scan preparation service account to consume Google Cloud APIs
resource "google_project_iam_member" "doc_processor_service_usage" {
  project = var.project_id
  role    = "roles/serviceusage.serviceUsageConsumer"
  member  = "serviceAccount:${google_service_account.doc_processor_sa.email}"
}

# Document scan preparation function source code archive
# Contains the built and zipped document scan preparation function
# Generated by the build process and deployed to Cloud Functions
resource "google_storage_bucket_object" "doc_processor_zip" {
  name   = "doc-processor.zip"
  bucket = var.function_bucket_name
  source = "../dist/functions/doc-processor.zip"
}

# Google Cloud Function v2 - Document Scan Preparation
# Event-driven function triggered by PubSub messages containing Google Drive file IDs
# Downloads files from Google Drive and copies them to Cloud Storage
# Provides document preparation for downstream processing
resource "google_cloudfunctions2_function" "doc_processor" {
  name        = "${var.environment}-doc-processor"
  description = "Prepares documents for scanning by copying Google Drive files to Cloud Storage (${var.environment})"
  location    = var.region

  build_config {
    runtime     = "nodejs20"
    entry_point = "docProcessor"
    source {
      storage_source {
        bucket     = var.function_bucket_name
        object     = google_storage_bucket_object.doc_processor_zip.name
        generation = google_storage_bucket_object.doc_processor_zip.generation
      }
    }
  }

  service_config {
    max_instance_count = 100
    min_instance_count = 0
    available_memory   = "512M"
    timeout_seconds    = 540
    environment_variables = {
      NODE_ENV   = "production"
      PROJECT_ID = var.project_id
    }
    service_account_email = google_service_account.doc_processor_sa.email
  }

  event_trigger {
    event_type   = "google.cloud.pubsub.topic.v1.messagePublished"
    pubsub_topic = google_pubsub_topic.doc_process_trigger.id
    retry_policy = "RETRY_POLICY_RETRY"
  }
}