import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// Autogenerated from the docs/ folder structure for now. The end-user
// information architecture (explicit sections and ordering) is defined in
// issue #339.
const sidebars: SidebarsConfig = {
  docsSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
