import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// Autogenerated from the docs/ folder structure. Section grouping and order
// are driven by each folder's _category_.json (position) and per-page
// sidebar_position, so adding a page only requires dropping a file in.
const sidebars: SidebarsConfig = {
  docsSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
