# PubSub topic for triggering Google Drive folder scans
# Receives scheduled messages from Cloud Scheduler
# Initiates the drive document scanner function
resource "google_pubsub_topic" "folder_scan_trigger" {
  name = "folder-scan-trigger"
}

# Dedicated service account for the drive scanner function
# Accesses Google Drive through manual folder sharing (not project-level IAM)
# Includes permissions for API access and PubSub publishing
resource "google_service_account" "folder_scanner_sa" {
  account_id   = "folder-scanner"
  display_name = "Drive File Manager Service Account"
  description  = "Service account for Google Drive access via folder sharing and PubSub publishing"
}

# IAM binding for Google Cloud Storage access - Folder Scanner
# Grants read access to storage objects for the folder scanner service account
resource "google_project_iam_member" "storage_access" {
  project = var.project_id
  role    = "roles/storage.objectViewer"
  member  = "serviceAccount:${google_service_account.folder_scanner_sa.email}"
}

# IAM binding for Google API service usage
# Allows the service account to consume Google Cloud APIs
# Required for accessing Drive API and other Google services
resource "google_project_iam_member" "service_usage" {
  project = var.project_id
  role    = "roles/serviceusage.serviceUsageConsumer"
  member  = "serviceAccount:${google_service_account.folder_scanner_sa.email}"
}

# IAM binding for PubSub message publishing
# Grants permission to publish messages to PubSub topics
# Essential for the scanner to queue documents for classification
resource "google_project_iam_member" "pubsub_publisher" {
  project = var.project_id
  role    = "roles/pubsub.publisher"
  member  = "serviceAccount:${google_service_account.folder_scanner_sa.email}"
}

# Drive scanner function source code archive
# Contains the built and zipped drive document scanner function
# Generated by the build process and deployed to Cloud Functions
resource "google_storage_bucket_object" "folder_scanner_zip" {
  name   = "folder-scanner.zip"
  bucket = var.function_bucket_name
  source = "../dist/functions/folder-scanner.zip"
}

# Google Cloud Function v2 - Drive Document Scanner
# Event-driven function triggered by PubSub messages from the scheduler
# Scans specified Google Drive folders and publishes document metadata
# for downstream classification processing
resource "google_cloudfunctions2_function" "folder_scanner" {
  name        = "folder-scanner"
  description = "Automated Google Drive scanner that discovers documents and queues them for classification processing"
  location    = var.region

  build_config {
    runtime     = "nodejs20"
    entry_point = "folderScanner"
    source {
      storage_source {
        bucket     = var.function_bucket_name
        object     = google_storage_bucket_object.folder_scanner_zip.name
        generation = google_storage_bucket_object.folder_scanner_zip.generation
      }
    }
  }

  service_config {
    max_instance_count = 10
    min_instance_count = 0
    available_memory   = "512M"
    timeout_seconds    = 300
    environment_variables = {
      NODE_ENV                        = "production"
      DOCUMENT_SCAN_PREPARATION_TOPIC = var.document_scan_preparation_topic_name
    }
    service_account_email = google_service_account.folder_scanner_sa.email
  }

  event_trigger {
    event_type   = "google.cloud.pubsub.topic.v1.messagePublished"
    pubsub_topic = google_pubsub_topic.folder_scan_trigger.id
    retry_policy = "RETRY_POLICY_RETRY"
  }
}